---
- name: Install Package
  hosts: all
  vars:
  - package_name: httpd

  tasks:
  - name: fetch mirror config
    get_url:
      url: http://workstation.example.com/pub/mirror.repo
      dest: /etc/yum.repos.d/mirror.repo

  - name: install yum-utils
    yum:
      name: http://workstation.example.com/repo/rhel-7-server-rpms/Packages/yum-utils-1.1.31-45.el7.noarch.rpm
      state: installed
      
  - name: enable repos
    shell: yum-config-manager --enable rhel-7-server-extras-rpms --enable rhel-7-server-optional-rpms &> /dev/null

  - name: install package {{ package_name }}
    yum: name={{ package_name }} state=present
